default:
  image: docker:24.0.2-git
  services:
    - docker:24.0.2-dind

stages:
  - login
  - build-action-server
  - build-flask-app
  - push-action-server
  - push-flask-app
  - logout

login_job:
  stage: login
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_action_server_job:
  stage: build-action-server
  script:
    - cd code/actions/
    - docker build -t $CI_REGISTRY/action-server .

build_flask_job:
  stage: build-flask-app
  script:
    - cd code/web_app/
    - docker build -t $CI_REGISTRY/flask_app .

push_action_server_job:
  stage: push-action-server
  script:
    - docker push --all-tags $CI_REGISTRY/action-server 

push_flask_app_job:
  stage: push-flask-app
  script:
    - docker push --all-tags $CI_REGISTRY/flask_app 

logout_job:
  stage: logout
  script:
    - docker logout $CI_REGISTRY