default:
  image: docker:24.0.2-git
  services:
    - docker:24.0.2-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build-action-server
  - build-flask-app
  - logout

build_action_server:
  stage: build-action-server
  script:
    - cd code/actions/
    - docker build -t $CI_REGISTRY_IMAGE/action-server .
    - docker push --all-tags $CI_REGISTRY_IMAGE/action-server

build_flask:
  stage: build-flask-app
  script:
    - cd code/web_app/
    - docker build -t $CI_REGISTRY_IMAGE/flask_app .
    - docker push --all-tags $CI_REGISTRY_IMAGE/flask_app

logout_job:
  stage: logout
  script:
    - docker logout $CI_REGISTRY