stages:
  - build

build:
  image: docker:24.0.2-git
  stage: build
  services:
    - docker:24.0.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  script:
    - docker build -t my-docker-image .