image: docker:24.0.2-git
services:
  - docker:24.0.2-dind
stages:
  - login
  - build-rasa-server
  - build-action-server
  - build-flask-app
  - push-rasa-server
  - push-action-server
  - push-flask-app
  - logout

login_job:
  stage: login
  tags:
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_rasa_server_job:
  stage: build-rasa-server
  tags:
    - docker
  script:
    - docker build -t rasa-server code/ .
build_action_server_job:
  stage: build-action-server
  tags:
    - docker
  script:
    - docker build -t action-server code/actions .

build_flask_job:
  stage: build-flask-app
  tags:
    - docker
  script:
    - docker build -t flask_app code/web_app .

push_rasa_server_job:
  stage: push-rasa-server
  tags:
    - docker
  script:
    - docker push rasa-server

push_action_server_job:
  stage: push-action-server
  tags:
    - docker
  script:
    - docker push action-server

push_flask_app_job:
  stage: push-flask-app
  tags:
    - docker
  script:
    - docker push flask_app

logout_job:
  stage: logout
  tags:
    - docker
  script:
    - docker logout $CI_REGISTRY
# build:
#   image: docker:24.0.2-git
#   stage: build
#   services:
#     - docker:24.0.2-dind
#   # variables:
#   #   DOCKER_TLS_CERTDIR: "/certs"

#   script:
#     - docker build -t my-docker-image .
