version: '3'
services:
    rasa_server:
      image: kerfmeliodas/rasa-server-tb:latest
      container_name: "rasa_server"
      user: root
      volumes:
      - "./:/app"
      ports: 
        - "5005:5005"
      command:
        - run
        - --enable-api
        - --cors
        - "*"
    action_server:
      image: kerfmeliodas/rasa-action-server-tb
      container_name: "action_server"
      volumes:
        - ./actions:/app/actions
        - ./data:/app/data
        - ./functions:/app/functions
      ports:
        - 5055:5055
      restart: always  
    graphdb_server:
      image: ontotext/graphdb:10.2.2
      container_name: "graphdb-server"
      volumes:
        - ./graphdb:/opt/graphdb/home
      ports:
        - 7200:7200
      restart: always   
    web_app:    
      image: kerfmeliodas/flask-app-tb:latest2
      container_name: flask_app_tb
      ports:
        - 5000:5000
      restart: always  
