version: '3'
services:
    rasa_server:
      image: kerfmeliodas/rasa-server-tb:latest
      container_name: "rasa_server"
      user: root
      volumes:
      - "./data:/app/data"
      ports: 
        - 5005:5005
      command:
        - run
        - --enable-api
        - --cors
        - "*"
    action_server:
      image: kerfmeliodas/rasa-action-server-tb:test
      container_name: "action_server"
      volumes:
        - ./data:/app/data # le folder data sera ajouté au container du serveur d'action
      ports:
        - 5055:5055
      restart: always  
    graphdb_server:
      image: ontotext/graphdb:10.2.2
      container_name: "graphdb-server"
      volumes:
        - ./graphdb:/opt/graphdb/home
      ports:
        - 7200:7200
      restart: always   
    web_app:    
      image: kerfmeliodas/flask-app-tb:do #  tag "do" pour digital ocean
      container_name: flask_app_tb
      ports:
        - 5000:5000
      links:
        - rasa_server  
      restart: always  
